### ISSUE TITLE
Add ESD protection to buzzer and external inputs

### ISSUE THREAD

**Issue by Miceuz** [RespiraWorks/pcbreathe#13]
Also buzzer and any physical button connections have to be ESD protected - they will sprinkle those with ESD gun in the test lab. Thus ESD protection on 12V rail.

**Comment by neelfirst** [comment]
We have TVS on the 12V input now that's 61000-4-x compliant. It _says_ it will survive a 30kV contact discharge...

Nothing on the buzzer yet, but if it's sealed within the vent box it just has to survive air discharge, not contact discharge.

I think we can revisit this issue when mechanical design is more intact, and we can plan for air discharge test locations.
