### ISSUE TITLE
Heater and solenoid connectors should be differentiated mechanically

### ISSUE THREAD

**Issue by toybuilder** [RespiraWorks/pcbreathe#15]
The heater and solenoid connections are both 2-pin XH connectors and are adjacent.  It would be easy to mix the two connectors up during assembly.  

To minimize errors and speed up assembly (because you don't have to pay attention if the connectors couldn't get mixed up), I suggest making the heater connector 3-pinned so that the heater cable plug can't go into the solenoid socket.  The additional third pin could potentially be reserved for a thermistor connection for the heater.

**Comment by inceptionev** [comment]
Good thinking.  Implemented.

**Comment by neelfirst** [comment]
Confirmed. Heater has a 3-pin output (pin 3 NC) and solenoid has 2-pin output.
