### ISSUE TITLE
Add more i2c connection points + i2c multiplexer

### ISSUE THREAD

**Issue by brmurray** [RespiraWorks/pcbreathe#16]
If we shift towards flow sensors with integral transducers + boards, they'll probably move off the main pcb and communicate via I2C. A future iteration should include at least 4 I2C ports (2x for each of 2 venturi tubes), as well as an I2C multiplexer (eg TCA9544A)

**Comment by inceptionev** [comment]
added multiplexer and 4 i2c sensor ports

**Comment by inceptionev** [comment]
we may need to do something clever here to make sure that it isn't easy to plug the wrong sensors into the wrong plugs

**Comment by neelfirst** [comment]
This is implemented; are these sensors not addressable? Is that why the mux is needed?
