### ISSUE TITLE
Add microcontroller-readable hardware identification on the board 

### ISSUE THREAD

**Issue by Miceuz** [RespiraWorks/pcbreathe#17]
I think we will use it for tracing, identification, tests, etc. 

Thinking ahead, we will also need serial number for each board.

**Comment by neelfirst** [comment]
Verified HW IDs readable by RPI and STM. Created #31 as followup for prod.

**Comment by neelfirst** [comment]
Sorry need to reopen. Just noticed the CC IDs are tied to RPI_3V3 where they should be tied to CC_3V3.

**Comment by neelfirst** [comment]
confirmed, closed
