### ISSUE TITLE
Reverse input diode possible undersized

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/pcbreathe#19]
Rated for 5V, might require more (from Lee)

**Comment by inceptionev** [comment]
Also note if motor braking is added to the motor control, it might not be possible to have a diode here.

**Comment by neelfirst** [comment]
It's rated for 60V at 5A...

VF for this diode is 0.7V so if we design for Vout = 5 @ 2 A then the input current (assume 9V) is 1.1 A so power dissipated will be 0.77 W, which will raise Tja by 38.5 C. As it can handle 125 C this isn't a concern.

https://www.diodes.com/assets/Datasheets/ds13012.pdf

**Comment by inceptionev** [comment]
Removing this diode for Alpha.  I think it's a reasonable expectation for the power to get plugged in correctly.  This diode is going to cause problems anyways if we go to a 4-quadrant motor controller.
