### ISSUE TITLE
Export schematics to .pdf and pcb to gerber

### ISSUE THREAD

**Issue by NoahGWood** [RespiraWorks/pcbreathe#2]
Is it possible for the maintainer to export the schematics to pdf and the pcb files to gerber when pushing updates? I use KiCAD so I've got to convert the files to work with kicad and then manually verify and link each file, bit time consuming

**Comment by inceptionev** [comment]
gerbers added to the NIGHTLY subdirectory, let me know if that works

**Comment by inceptionev** [comment]
been trying to use the altium2kicad tool myself and I agree...it's more of a struggle than I anticipated.

**Comment by neelfirst** [comment]
gerbers present, closing
