### ISSUE TITLE
Evaluate voltage sensor source resistance 

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/pcbreathe#23]
(from Lee)

**Comment by inceptionev** [comment]
Good to check.  The STM32 ADC sampling cap is 5pF, given worst case 3.3V swing and 500hz sampling, the average current draw is 8.25nA, which against a 6.7kohm thevenin source resistance is 55uV, and the instantaneous charge drop against the 0.22uF cap is 75uV, for a total worst case error of 130uV.  The LSB for a the 12bit ADC referenced at 3.3V is 806uV.  The worst case error is less than 1/2 LSB.  We should be good.

**Comment by inceptionev** [comment]
Switched R_hi to 35.7k to change to 3.3V scaling.  This changes the thevenin resistance to 7.8k, which represents an increase of 6uV to 64uV, still well below 1/2 LSB when combined with the sampling charge balance.

**Comment by neelfirst** [comment]
confirmed
