### ISSUE TITLE
Hardware serialization for PCBs

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/pcbreathe#31]
This is a production feature.

Followup from #17 - add hardware serial numbers for PCBs.

This could be a traditional R-based board ID, but I've used EEPROM for this as well (non-medical)

**Comment by inceptionev** [comment]
There are unique ID ICs we could use, or yeah burn them into an EEPROM

**Comment by sglow** [comment]
We can just store it in the flash memory of the STM32, or in the OTP (One Time Programmable) section of flash if we're paranoid

**Comment by KennethLaws** [comment]
I think that we can say this is closed from a hardware perspective.  Hardware serialization will be stored in non-volitile memory.  @neelfirst Is this issue tracked by software elsewhere?  If so, I would like to close this here.

**Comment by neelfirst** [comment]
Opened https://github.com/RespiraWorks/VentilatorSoftware/issues/376, closing this.
