### ISSUE TITLE
Non-ideal UART connected to Pi from Nucleo

### ISSUE THREAD

**Issue by verityRF** [RespiraWorks/pcbreathe#32]
So the RXD/TXD pins that are marked on the Nucleo dev board are link to both the 19x2 header and to the STLink USB debug chip onboard. This means that any communications between the Pi and the Nucleo would interfere with debugging from the PC that would hugely gain from having that serial access over USB from a dev standpoint. Furthermore, any debug messages sent to the Nucleo would interfere with the same link. 

1) Having dev access to the built-in serial pins that are by default connected to the USB debugger is extremely valuable (can print various controller/sensor values over time over serial and have it show up on the host x86 PC for analysis)
2) Having the controller link also shared will cause a lot of headache, especially with introducing potential timing headaches during troubleshooting and debug

I would recommend putting PA2/PA3 (TXD/RXD labeled on the Nucleo) as NC. 

Then use any of the following pins for the Pi link: (See #33 too before fixing this)
MCU Pin Fn Alt Name -> MCU Pin #

USART3 TX -> PB10
USART3 RX -> PB11

USART3 TX -> PC4
USART3 RX -> PC5

USART3 TX -> PC10
USART3 RX -> PC11

USART4 TX -> PA0
USART4 RX -> PA1

USART1 TX -> PA9
USART1 RX -> PA10

USART1 TX -> PB6
USART1 RX -> PB7

All channels are functionally equivalent. USART2 is the one connected to the STLink debugger on the dev board.

For those unfamiliar with ARM, yes those functions are not shown on the Nucleo or marked on the PCB. All Cortex-M parts have internal configurable pin muxing that allows you to map specific multiple pins to an internal peripheral through software configuration. Yes those pins may look funny, but they're from the datasheet!

**Comment by inceptionev** [comment]
great catch!

**Comment by inceptionev** [comment]
Implemented using USART3 with flow control signals

**Comment by neelfirst** [comment]
I confirmed this change has happened.
