### ISSUE TITLE
Solenoid back EMF

### ISSUE THREAD

**Issue by rkevinwatson** [RespiraWorks/pcbreathe#35]
Can the design handle the back EMF when the field collapses at the solenoid?

**Comment by neelfirst** [comment]
There is a flyback diode across the solenoid terminals... do you expect something more?

Since it's being driven only one way (i.e. no negative voltage) I think this is sufficient.

Happy to be corrected.

**Comment by rkevinwatson** [comment]
Okay, cool. It seems like a pretty beefy diode, I just raised a flag to ensure it's beefy enough to handle the energy that it might get hit with.

**Comment by neelfirst** [comment]
You're right this is worth noting. So for this issue record the S8MC-13 is spec'd at 1kV/8A. Thanks :)
