### ISSUE TITLE
Use locking power input connector for J1 in later board revisions.

### ISSUE THREAD

**Issue by rkevinwatson** [RespiraWorks/pcbreathe#37]
For later revisions of the board consider using a locking-type connector instead of a barrel connector for twelve volt power input at J1.

**Comment by inceptionev** [comment]
recommend JST PH series for common worldwide availability

**Comment by inceptionev** [comment]
recommend JST VH for common worldwide availability

**Comment by inceptionev** [comment]
Implemented in alpha since we have the parts, using 3-pin VH connector so as not to be swappable with the motor power connector

**Comment by inceptionev** [comment]
ready for review and close

**Comment by rkevinwatson** [comment]
Checked schematic and BOM and it's still a barrel connector. Should we pass on this change until next revision?

**Comment by inceptionev** [comment]
If you check the Altium files the new connector should be in there.  Once I do an export for mfg, the PDF schematics and gerbers in the NIGHTLY folder will also reflect this.

**Comment by inceptionev** [comment]
that's coming in like 10min

**Comment by rkevinwatson** [comment]
Okay, cool. I checked power.sch and the connector has been changed, Closing this issue.
