### ISSUE TITLE
Add motor power connector

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/pcbreathe#38]
need a connector to power the motor driver.  Use JST VH

**Comment by neelfirst** [comment]
Which motor is this, that runs 12V continuously? Or is this intended to act as a jumper to another dev board for motor control?

**Comment by inceptionev** [comment]
this is the power that goes to the blower driver board.  This has been implemented with a JST VH connector.

**Comment by neelfirst** [comment]
:+1:
