### ISSUE TITLE
complete alarm implementation

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/pcbreathe#4]

**Comment by inceptionev** [comment]
added alarm LEDs, initial design complete, but should double check buzzer selection/availability.

**Comment by neelfirst** [comment]
Ouch yeah stock is not looking good for https://octopart.com/search?q=PLD-21N30PQ&currency=USD&specs=0

Meanwhile this one is more widely available, and is slightly louder: https://www.digikey.com/product-detail/en/mallory-sonalert-products-inc/PLD-27A35PQ/458-1529-ND/1957909

**Comment by neelfirst** [comment]
Since this alarm is of a different footprint, it blocks fab

**Comment by inceptionev** [comment]
alarm has been switched out in issue #29 and implemented
