### ISSUE TITLE
Power: C5 and C36 voltage rating

### ISSUE THREAD

**Issue by rkevinwatson** [RespiraWorks/pcbreathe#40]
Suggest bumping up the voltage rating of C5 and C36 to ten, preferably sixteen volts.

**Comment by neelfirst** [comment]
setting this to post-fab as this can be solved in BOM. but the schematic should get updated.

sanity check: digikey has 16V 0603 ceramic at the listed footprints (1u/0603, 47u/1206)

**Comment by inceptionev** [comment]
done.  Converted C36 and C5 to 10V X7R.  Also converted all 1uF 6.3V caps to the same 1uF 10V cap for BOM consolidation

**Comment by inceptionev** [comment]
this ticket is ready for review and closure

**Comment by rkevinwatson** [comment]
Checked schematic and the caps are indeed ten volt parts. Closing this issue.
