### ISSUE TITLE
consider adding a stepper driver

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/pcbreathe#44]

**Comment by inceptionev** [comment]
this will allow us to more prototyping options.

we could possibly use one of the i2c ports to attach an i2c stepper driver such as AMIS 30624

**Comment by neelfirst** [comment]
https://www.st.com/en/ecosystems/x-nucleo-ihm03a1.html 

Nucleo shield for stepper motor driver

**Comment by neelfirst** [comment]
I documented the pin difference between the Nucleo stepper driver and Edwin's board here.
I created separate tabs that just display the pin conflicts, along with my proposed resolution.
The thrust of the idea is to share the SPI bus across uSD and the stepper, with different chip selects.
Alternatively we could just remove the uSD card when testing the stepper motor.

I'd like a review from @verityRF @inceptionev @rkevinwatson to make sure I didn't go crosseyed making the pin charts. I'm particularly susceptible to MOSI/MISO mixups.

https://docs.google.com/spreadsheets/d/1EP9jQYIz0WdIBkeFmQDyeVXeIfuUcTSwAgnJIIQ7mOM/edit?usp=sharing

**Comment by neelfirst** [comment]
@sosaysthecaptain

**Comment by inceptionev** [comment]
I don't think switching the solenoid control from CN8p21 to CN8p24 is going to work because CN8p24  is on TIM3, which ties the solenoid PWM to the buzzer frequency.  There is a TIM1 output on this pin but it is inverted.  Not sure if that will be a problem but it would be ideal to use a pin with the positive polarity.

**Comment by inceptionev** [comment]
Proposed solution: use CN10p24 (PB1) for CC-ID0 and use CN10p14 (PA11/TIM1CH4) for solenoid control.

**Comment by inceptionev** [comment]
Please review the attached schematic to confirm the pin swaps
[20200423-Issue44review-RespiraWorks-Ventilator-DWG-SCH.pdf](https://github.com/RespiraWorks/pcbreathe/files/4526548/20200423-Issue44review-RespiraWorks-Ventilator-DWG-SCH.pdf)

**Comment by inceptionev** [comment]
Also please verify, all these pins seem to be on CN10, not CN8

**Comment by neelfirst** [comment]
Approved! I updated the spreadsheet linked above, with a new tab 'FINAL' detailing this change.

**Comment by neelfirst** [comment]
BTW a clerical error on my part, CN10, not CN8
