### ISSUE TITLE
Add mounting hardware to BOM

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/pcbreathe#46]
Followup from @toybuilder comment in #7:

"Related to this, I recommend adding BOM-entry components in the schematic to track what screws/standoffs/etc. are needed for the entire electronics sub-assembly so that the finished sub-assembly can be treated as a single FRU (field replaceable unit) in the larger context of the entire machine."

**Comment by inceptionev** [comment]
I'll put them on the BOM as DNP so as not to confuse the board house

**Comment by inceptionev** [comment]
added parts to the schematic that will show up on BOM, DNP'd for this build so as not to confuse board house sourcing (the computing modules are also DNP'd)

**Comment by inceptionev** [comment]
implemented, ready to review for close

**Comment by KennethLaws** [comment]
mechanical parts have been added.  This seems sufficient to close the issue
