### ISSUE TITLE
uSD rotate 180(?)

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/pcbreathe#48]
I _think_ J4 is rotated 180, so you would have to insert the usd card from the inside.

This happened to me once, I don't recommend it >_<

**Comment by inceptionev** [comment]
According to the drawing it appears to be correct as placed: 
![image](https://user-images.githubusercontent.com/8660661/80197017-f2b81c80-85d2-11ea-9d14-34c5d994ee1e.png)

i.e., card enters from the side where the PCB contacts are.

**Comment by neelfirst** [comment]
Wow strange. Ok then!
