### ISSUE TITLE
Connectors - all R/A

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/pcbreathe#49]
It could help with assembly wiring and harness design to have them all come out at the edge.

@ebhillstrom opinions on direction of cabling / wiring harness coming out of the PCB? 

In the assembly, would you prefer cabling be flush to the PCB mounting surface or orthogonal to it?

**Comment by inceptionev** [comment]
We should get @ebhillstrom's thoughts on this, but my thinking was that straight connectors would be better given how crammed the panel is, i.e. not necessarily room to maneuver connectors once the vent is assembled.  Is this a gating issue for alpha?

**Comment by neelfirst** [comment]
My bad. I'm having difficulty conjuring the latest mechanical design files. Do we then need a vertical barrel jack?

**Comment by neelfirst** [comment]
Per https://respiraworks.slack.com/archives/C011KC7TF46/p1587744941210200 the vote is to keep it your way, @inceptionev. So I guess we're good here.

**Comment by inceptionev** [comment]
The barrel jack was a convenience item for alpha-as-dev-tool assuming everyone has a 12v 5.5x2.1mm wall adapter at home.  This will be replaced with a locking header in beta (in whatever orientation we settle on)
