### ISSUE TITLE
define physical outline and mounting with mech team

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/pcbreathe#7]

**Comment by toybuilder** [comment]
Related to this, I recommend adding BOM-entry components in the schematic to track what screws/standoffs/etc. are needed for the entire electronics sub-assembly so that the finished sub-assembly can be treated as a single FRU (field replaceable unit) in the larger context of the entire machine.

**Comment by neelfirst** [comment]
tagging @ebhillstrom let's button this down

**Comment by neelfirst** [comment]
Closing per https://respiraworks.slack.com/archives/C0111E2GFPF/p1587644864459200?thread_ts=1587545496.440900&cid=C0111E2GFPF

Created followup issue #46 for HW in BOM
