### ISSUE TITLE
testpoints/DFT/DFM

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/pcbreathe#8]

**Comment by neelfirst** [comment]
Let's just scope this to testpoints, which we still need for alpha

**Comment by neelfirst** [comment]
From #30 - need a testpt at the power rails, esp 3.3V since the 150mA LDO on the Nucleo may not provide enough oomph for everything.

**Comment by inceptionev** [comment]
Ha, and the Pi's is even weaker.  I'll add the TP and we'll have a beefier supply on beta

**Comment by neelfirst** [comment]
TPs on SPI bus to microSD card? Your call.

**Comment by neelfirst** [comment]
I got a Nucleo board today and missed the obvious - they have double sided male headers on every pin. So test points on any of the CNx pins are pointless - we have them already.
